-- Migration 087: Managed tool definitions
-- Adds persistent, reviewable tool definitions that can be granted to agents
-- and executed through Lucent's sandbox/runtime wrapper.

CREATE TABLE IF NOT EXISTS managed_tool_definitions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(64) NOT NULL,
    description TEXT NOT NULL DEFAULT '',

    -- Model-visible contract
    input_schema JSONB NOT NULL DEFAULT '{"type":"object","properties":{}}'::jsonb,
    output_schema JSONB DEFAULT NULL,

    -- Execution contract. The first runtime implementation is python source
    -- executed inside a sandbox container. Future runtime types can reuse this
    -- table without changing the ownership/approval model.
    runtime_type VARCHAR(32) NOT NULL DEFAULT 'python'
        CHECK (runtime_type IN ('python')),
    source_code TEXT NOT NULL DEFAULT '',
    entrypoint VARCHAR(128) NOT NULL DEFAULT 'handler',
    requirements JSONB NOT NULL DEFAULT '[]'::jsonb,
    runtime_config JSONB NOT NULL DEFAULT '{}'::jsonb,

    -- Runtime guardrails
    env_vars JSONB NOT NULL DEFAULT '{}'::jsonb,
    auth_policy JSONB NOT NULL DEFAULT '{"mode":"agent_grant","require_user_access":true}'::jsonb,
    network_policy JSONB NOT NULL DEFAULT '{"network_mode":"none","allowed_hosts":[]}'::jsonb,
    resource_limits JSONB NOT NULL DEFAULT '{"memory_limit":"512m","cpu_limit":1.0,"disk_limit":"1g","timeout_seconds":300}'::jsonb,
    timeout_seconds INTEGER NOT NULL DEFAULT 300 CHECK (timeout_seconds BETWEEN 1 AND 3600),

    status VARCHAR(16) NOT NULL DEFAULT 'proposed'
        CHECK (status IN ('proposed', 'active', 'rejected', 'archived')),
    scope VARCHAR(16) NOT NULL DEFAULT 'instance'
        CHECK (scope IN ('instance', 'built-in')),

    created_by UUID REFERENCES users(id) ON DELETE SET NULL,
    approved_by UUID REFERENCES users(id) ON DELETE SET NULL,
    approved_at TIMESTAMPTZ,
    organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    owner_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    owner_group_id UUID REFERENCES groups(id) ON DELETE SET NULL,
    proposal_reason TEXT,
    proposal_evidence JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (name, organization_id),
    CONSTRAINT ck_managed_tool_single_owner
        CHECK (NOT (owner_user_id IS NOT NULL AND owner_group_id IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS idx_managed_tool_defs_org_status
    ON managed_tool_definitions(organization_id, status);
CREATE INDEX IF NOT EXISTS idx_managed_tool_defs_owner_user
    ON managed_tool_definitions(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_managed_tool_defs_owner_group
    ON managed_tool_definitions(owner_group_id);
CREATE INDEX IF NOT EXISTS idx_managed_tool_defs_org_shared
    ON managed_tool_definitions(organization_id, status, name)
    WHERE scope = 'instance' AND owner_user_id IS NULL AND owner_group_id IS NULL;

CREATE TABLE IF NOT EXISTS agent_managed_tools (
    agent_id UUID NOT NULL REFERENCES agent_definitions(id) ON DELETE CASCADE,
    tool_id UUID NOT NULL REFERENCES managed_tool_definitions(id) ON DELETE CASCADE,
    config_override JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (agent_id, tool_id)
);

CREATE INDEX IF NOT EXISTS idx_agent_managed_tools_tool
    ON agent_managed_tools(tool_id);

CREATE TABLE IF NOT EXISTS managed_tool_runs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tool_id UUID NOT NULL REFERENCES managed_tool_definitions(id) ON DELETE CASCADE,
    agent_id UUID REFERENCES agent_definitions(id) ON DELETE SET NULL,
    user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    sandbox_id UUID,
    status VARCHAR(16) NOT NULL DEFAULT 'running'
        CHECK (status IN ('running', 'completed', 'failed', 'blocked')),
    input_payload JSONB,
    output_payload JSONB,
    error TEXT,
    duration_ms INTEGER,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_managed_tool_runs_tool_started
    ON managed_tool_runs(tool_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_managed_tool_runs_org_started
    ON managed_tool_runs(organization_id, started_at DESC);

COMMENT ON TABLE managed_tool_definitions IS 'Persistent approved/proposed tools generated by the tool builder and executed through sandbox runtime wrappers.';
COMMENT ON COLUMN managed_tool_definitions.auth_policy IS 'Default mode agent_grant requires caller access to the tool and an agent grant when invoked from an agent context.';
COMMENT ON COLUMN managed_tool_definitions.network_policy IS 'Sandbox network policy. Default is no outbound network; allowlist mode requires explicit allowed_hosts.';
COMMENT ON TABLE agent_managed_tools IS 'Grants managed tools to agent definitions.';
COMMENT ON TABLE managed_tool_runs IS 'Execution records for sandbox-backed managed tool calls.';
