-- Migration 116 rollback: drop every tenant policy, then remove the RLS
-- binding. Order matters: policies must be dropped before FORCE is lifted,
-- and FORCE before DISABLE (dropping policies is what releases the binding;
-- the ALTERs restore the pre-wave state).

DROP POLICY IF EXISTS p_admin_audit_log_tenant ON public.admin_audit_log;
DROP POLICY IF EXISTS p_agent_definitions_tenant ON public.agent_definitions;
DROP POLICY IF EXISTS p_agent_hooks_tenant ON public.agent_hooks;
DROP POLICY IF EXISTS p_agent_managed_tools_tenant ON public.agent_managed_tools;
DROP POLICY IF EXISTS p_agent_mcp_servers_tenant ON public.agent_mcp_servers;
DROP POLICY IF EXISTS p_agent_skills_tenant ON public.agent_skills;
DROP POLICY IF EXISTS p_api_keys_tenant ON public.api_keys;
DROP POLICY IF EXISTS p_daemon_instances_tenant ON public.daemon_instances;
DROP POLICY IF EXISTS p_enterprise_credentials_tenant ON public.enterprise_credentials;
DROP POLICY IF EXISTS p_github_repo_access_cache_tenant ON public.github_repo_access_cache;
DROP POLICY IF EXISTS p_hook_definitions_tenant ON public.hook_definitions;
DROP POLICY IF EXISTS p_integrations_tenant ON public.integrations;
DROP POLICY IF EXISTS p_llm_messages_tenant ON public.llm_messages;
DROP POLICY IF EXISTS p_llm_session_events_tenant ON public.llm_session_events;
DROP POLICY IF EXISTS p_llm_session_requests_tenant ON public.llm_session_requests;
DROP POLICY IF EXISTS p_llm_sessions_tenant ON public.llm_sessions;
DROP POLICY IF EXISTS p_llm_token_usage_tenant ON public.llm_token_usage;
DROP POLICY IF EXISTS p_managed_tool_definitions_tenant ON public.managed_tool_definitions;
DROP POLICY IF EXISTS p_managed_tool_runs_tenant ON public.managed_tool_runs;
DROP POLICY IF EXISTS p_mcp_server_configs_tenant ON public.mcp_server_configs;
DROP POLICY IF EXISTS p_memories_tenant ON public.memories;
DROP POLICY IF EXISTS p_memory_access_grants_tenant ON public.memory_access_grants;
DROP POLICY IF EXISTS p_memory_access_log_tenant ON public.memory_access_log;
DROP POLICY IF EXISTS p_memory_audit_log_tenant ON public.memory_audit_log;
DROP POLICY IF EXISTS p_memory_shadow_scores_tenant ON public.memory_shadow_scores;
DROP POLICY IF EXISTS p_oauth2_state_challenges_tenant ON public.oauth2_state_challenges;
DROP POLICY IF EXISTS p_pairing_challenges_tenant ON public.pairing_challenges;
DROP POLICY IF EXISTS p_projects_tenant ON public.projects;
DROP POLICY IF EXISTS p_request_memories_tenant ON public.request_memories;
DROP POLICY IF EXISTS p_request_views_tenant ON public.request_views;
DROP POLICY IF EXISTS p_requests_tenant ON public.requests;
DROP POLICY IF EXISTS p_resource_access_grants_tenant ON public.resource_access_grants;
DROP POLICY IF EXISTS p_reviews_tenant ON public.reviews;
DROP POLICY IF EXISTS p_sandbox_templates_tenant ON public.sandbox_templates;
DROP POLICY IF EXISTS p_sandboxes_tenant ON public.sandboxes;
DROP POLICY IF EXISTS p_schedule_runs_tenant ON public.schedule_runs;
DROP POLICY IF EXISTS p_schedules_tenant ON public.schedules;
DROP POLICY IF EXISTS p_secrets_tenant ON public.secrets;
DROP POLICY IF EXISTS p_skill_definitions_tenant ON public.skill_definitions;
DROP POLICY IF EXISTS p_task_events_tenant ON public.task_events;
DROP POLICY IF EXISTS p_task_memories_tenant ON public.task_memories;
DROP POLICY IF EXISTS p_task_outputs_tenant ON public.task_outputs;
DROP POLICY IF EXISTS p_tasks_tenant ON public.tasks;
DROP POLICY IF EXISTS p_tool_call_audit_log_tenant ON public.tool_call_audit_log;
DROP POLICY IF EXISTS p_user_file_revisions_tenant ON public.user_file_revisions;
DROP POLICY IF EXISTS p_user_file_views_tenant ON public.user_file_views;
DROP POLICY IF EXISTS p_user_files_tenant ON public.user_files;
DROP POLICY IF EXISTS p_user_groups_tenant ON public.user_groups;
DROP POLICY IF EXISTS p_user_interaction_messages_tenant ON public.user_interaction_messages;
DROP POLICY IF EXISTS p_user_interaction_references_tenant ON public.user_interaction_references;
DROP POLICY IF EXISTS p_user_interaction_views_tenant ON public.user_interaction_views;
DROP POLICY IF EXISTS p_user_interactions_tenant ON public.user_interactions;
DROP POLICY IF EXISTS p_user_links_tenant ON public.user_links;

-- Un-bind: disable and un-force RLS on every table 115 touched.
ALTER TABLE public.admin_audit_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_audit_log NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.agent_definitions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_definitions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.agent_hooks DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_hooks NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.agent_managed_tools DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_managed_tools NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.agent_mcp_servers DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_mcp_servers NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.agent_skills DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_skills NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.api_keys DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_keys NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.daemon_instances DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.daemon_instances NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.enterprise_credentials DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.enterprise_credentials NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.github_repo_access_cache DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.github_repo_access_cache NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.hook_definitions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.hook_definitions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.integrations DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.integrations NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.llm_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.llm_messages NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.llm_session_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.llm_session_events NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.llm_session_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.llm_session_requests NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.llm_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.llm_sessions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.llm_token_usage DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.llm_token_usage NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.managed_tool_definitions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.managed_tool_definitions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.managed_tool_runs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.managed_tool_runs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.mcp_server_configs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.mcp_server_configs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.memories DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.memories NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.memory_access_grants DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.memory_access_grants NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.memory_access_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.memory_access_log NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.memory_audit_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.memory_audit_log NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.memory_shadow_scores DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.memory_shadow_scores NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.oauth2_state_challenges DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.oauth2_state_challenges NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.pairing_challenges DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.pairing_challenges NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.request_memories DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.request_memories NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.request_views DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.request_views NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.requests NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.resource_access_grants DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.resource_access_grants NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.reviews DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.sandbox_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sandbox_templates NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.sandboxes DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sandboxes NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.schedule_runs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedule_runs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.schedules DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedules NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.secrets DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.secrets NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.skill_definitions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.skill_definitions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.task_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_events NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.task_memories DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_memories NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.task_outputs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_outputs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.tool_call_audit_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.tool_call_audit_log NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.user_file_revisions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_file_revisions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.user_file_views DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_file_views NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.user_files DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_files NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.user_groups DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_groups NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.user_interaction_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_interaction_messages NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.user_interaction_references DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_interaction_references NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.user_interaction_views DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_interaction_views NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.user_interactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_interactions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.user_links DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_links NO FORCE ROW LEVEL SECURITY;