{{- if .Values.server.fileStorage.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-user-files" (include "lucent.fullname" .) }}
  labels:
    {{- include "lucent.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.server.fileStorage.persistence.size }}
  {{- with .Values.server.fileStorage.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}