apiVersion: v2
name: lucent
description: Helm chart for deploying Lucent and optional embedded dependencies
type: application
version: 0.1.0
appVersion: "0.2.0"
dependencies:
  - name: postgresql
    version: "16.7.21"
    repository: "https://charts.bitnami.com/bitnami"
    condition: database.embedded
